name: "Build jlm"
description: "Configures and builds jlm along with the necessary dependencies."

inputs:
  cxx:
    description: "Set C++ compiler."
    required: true

runs:
  using: "composite"
  steps:
    - name: "Clone jlm"
      run: git clone https://github.com/phate/jlm.git /tmp/jlm
      shell: bash

    - name: "Configure jlm"
      run: |
        cwd=$(pwd) && \
        cd /tmp/jlm && \
        ./configure.sh --target release --enable-asserts CXX=${{inputs.cxx}} && \
        cd ${cwd}
      shell: bash

    - name: "Compile jlm"
      run: make -C /tmp/jlm -j `nproc` -O all
      shell: bash

    - name: "Add executables to PATH"
      run: echo '/tmp/jlm/build' >> $GITHUB_PATH
      shell: bash