name: "Install packages"
description: "Installs packages that the llvm-test-suite depends on."

runs:
  using: "composite"
  steps:
    - name: "Get LLVM apt key"
      run: |
        export HAS_LLVM_REPOSITORY=$(find /etc/apt/ -name *.list | xargs cat | grep llvm-toolchain-jammy-16)
        if [[ -z $HAS_LLVM_REPOSITORY ]]; then
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo add-apt-repository --no-update deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main
        fi
      shell: bash

    - name: "Update apt sources"
      run: sudo apt-get update
      shell: bash

    - name: "Install LLVM and clang package"
      run: |
        sudo apt-get install llvm-16-dev clang-16
        pip install "lit~=16.0"
        pip show lit
      shell: bash