name: Tests

on:
  pull_request:
    branches: [ jlm-with-llvm-16 ]

jobs:
  llvm-test-suite:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.title, '[DisableCI]') == false
    steps:
    - uses: actions/checkout@v4
    - name: "Install packages"
      uses: ./.github/actions/InstallPackages
    - name: "Build jlm"
      uses: ./.github/actions/BuildJlm
    - name: "Run LLVM test suite"
      run: make -C jlm llvm-run-opt

  llvm-test-suite-andersen-agnostic:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.title, '[DisableCI]') == false
    steps:
    - uses: actions/checkout@v4
    - name: "Install packages"
      uses: ./.github/actions/InstallPackages
    - name: "Build jlm"
      uses: ./.github/actions/BuildJlm
    - name: "Run LLVM test suite"
      run: make -C jlm llvm-run-andersen-agnostic

  llvm-test-suite-steensgaard-agnostic:
    runs-on: ubuntu-22.04
    if: contains(github.event.pull_request.title, '[DisableCI]') == false
    steps:
    - uses: actions/checkout@v4
    - name: "Install packages"
      uses: ./.github/actions/InstallPackages
    - name: "Build jlm"
      uses: ./.github/actions/BuildJlm
    - name: "Run LLVM test suite"
      run: make -C jlm llvm-run-steensgaard-agnostic
